language: node_js
node_js:
  - "stable"
notifications:
  email: false

cache:
  directories:
  - node_modules

script:
  npm run build

deploy:
  provider: pages
  cleanup: true
  token: $GITHUB_TOKEN
  local_dir: build
  on:
    branch: master
