language: node_js
node_js:
  - "stable"
notifications:
  email: false

deploy:
  provider: pages
  cleanup: true
  token: $GITHUB_TOKEN
  keep_history: true
  local_dir: public
  on:
    branch: master
